# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_download_youtube(object):
    def setupUi(self, download_youtube):
        download_youtube.setObjectName("download_youtube")
        download_youtube.resize(380, 350)
        download_youtube.setMaximumSize(QtCore.QSize(380, 520))
        self.centralwidget = QtWidgets.QWidget(download_youtube)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.url_adress = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.url_adress.setObjectName("url_dadress")
        self.verticalLayout.addWidget(self.url_adress)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(100, 170, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.download_video = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.download_video.setObjectName("download_video")
        self.verticalLayout_2.addWidget(self.download_video)
        self.download_audio = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.download_audio.setObjectName("download_audio")
        self.verticalLayout_2.addWidget(self.download_audio)
        download_youtube.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(download_youtube)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 26))
        self.menubar.setObjectName("menubar")
        download_youtube.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(download_youtube)
        self.statusbar.setObjectName("statusbar")
        download_youtube.setStatusBar(self.statusbar)

        self.retranslateUi(download_youtube)
        QtCore.QMetaObject.connectSlotsByName(download_youtube)

    def retranslateUi(self, download_youtube):
        _translate = QtCore.QCoreApplication.translate
        download_youtube.setWindowTitle(_translate("download_youtube", "Загрузчик с ютуба"))
        self.url_adress.setPlaceholderText(_translate("download_youtube", "Ссылка на видео"))
        self.download_video.setText(_translate("download_youtube", "Скачать видео"))
        self.download_audio.setText(_translate("download_youtube", "Скачать аудио"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    download_youtube = QtWidgets.QMainWindow()
    ui = Ui_download_youtube()
    ui.setupUi(download_youtube)
    download_youtube.show()
    sys.exit(app.exec_())
